language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
before_script:
  - sudo apt-get update
  - export CXX=/usr/bin/g++-7
  - export CC=/usr/bin/gcc-7

script: 
  - cmake .
  - cmake --build .
  - cmake --build . --target package  
deploy: 
  - provider: script
    skip_cleanup: true
    script:       
     - curl -T yamr-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -upk-otus:$BINTRAY_API_KEY "https://api.bintray.com/content/pk-otus/OTUS/yamr/$TRAVIS_BUILD_NUMBER/yamr.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1" 
  
